name: Release website
on:
  push:
    branches: [main]
    tags: ["*"]
concurrency:
  group: release-${{ github.ref }}
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'sbt'
      - uses: sbt/setup-sbt@v1
      - name: Publish
        run: |
          sbt docs/docusaurusPublishGhpages
        env:
          GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}